auto: true
pygments: true
safe: true
lsi: false

markdown: rdiscount
maruku:
  extensions: [smart]

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

owner-name: Florian Holzner
owner-page: http://lebobs.ch/
owner-email: bobschi@lavabit.com

tagline: The mostly interesting ramblings of me ...