safe:        true
auto:        true
server:      true
baseurl:    /


future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /:year/:month/:title/

rdiscount:
  extensions: [smart]

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]
include: [""]

paginate: 3