auto: true
pygments: true
safe: true
lsi: false

markdown: rdiscount
maruku:
  extensions: [smart]

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

tagline: The mostly interesting ramblings of me ...