# theme config
title:            Le Bobsch Blogsch
description:      The personal blog of Florian Holzner
logo:             placeholder-logo.png
disqus_shortname: bobschi
search:           true
#Comment out url when working locally to resolve base urls correctly
url:              //lebobs.ch

# Owner/author information
owner:
  name:           bobschi
  avatar:         bobschi2.jpg
  email:          hello@lebobs.ch
  # Social networking links used in footer. Update and remove as you like.
  twitter:        bobschi
  facebook:       florianholzner
  github:         bobschi
  linkedin:       florianholzner
  #instagram:
  tumblr:         bobschi
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/116906205946090602685"

# Analytics and webmaster tools stuff goes here
#google_analytics:
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: "All Articles"
    url: /articles
  - title: "Personal Blog"
    url: /blog
  - title: "Music Blog"
    url: /musicblog
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Vienna
markdown:    kramdown
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty
category_dir: /
category_title_prefix: ""


# jekyll config
exclude: ["README.md", "LICENSE.md", "IDEAS.md", "TODO.md", "build", "test", "blog.sublime-project", "blog.sublime-workspace", "README.md", "IDEAS.md", "node_modules", "public", "_site"]

kramdown:
  smart_quotes: lsquo,rsquo,raquo,laquo

jekyll_compose:
  auto_open: true